### ISSUE TITLE
Missing payload schemas descriptions

### ISSUE THREAD

**Issue by gbougeard** [github/developer.github.com#996]
Hello,

I think there is a lack of documentation about json payloads.
If you want to develop a Github API client in a strong type language you need to know the type of each field and if a field is mandatory or not.
I also noticed that structures are not always the same. For example there is a `repository` structure in the PushPayload  https://developer.github.com/v3/activity/events/types/#pushevent which is lighter than the `repository` returned by the Repository service https://developer.github.com/v3/repos/#get . 
A clear description of these structures could help to define concise and precise typed structures in any language (instead of defining a big one with a lot of optional fields).

Unfortunately I think the community cannot help on this as the knowledge might be only in Github Dev teams hands.  Anyway, do you plan to expose those details?

**Comment by Shredder121** [comment]
I'm also doing something similar, what I do is I trigger each event and save the payload for future reference.
But a well defined schema should help much better.

I however think the community _can_ help, because there is a new `deployments_url` field in `repository` which is missing from the current payload examples.
It would be ideal if GitHub can keep these up to date, but if there is anything missing   we could amend that.

**Comment by mikemcquaid** [comment]
Hi @gbougeard and @Shredder121! Can you contact our support team? We're not accepting issues on this repository. Thanks!
